<a href="https://colab.research.google.com/github/nam5588/ai_foundation/blob/main/student_perfomance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('StudentsPerformance.csv')

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print("First 5 rows of the dataset:")
print(df.head())

print("Summary statistics")
print(df.describe())

print("Data type and null info:")
print(df.info ())

Dataset shape (rows, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
Summary statistics
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
Data type and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [39]:
print("Average score by subject:")
df[["math score", "reading score", "writing score"]].corr()

Average score by subject:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [40]:
print("Average score by subject:")
df[["math score", "reading score", "writing score"]].mean()

Average score by subject:

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [41]:
print("Max score by subject:")
df[["math score", "reading score", "writing score"]].max()

Max score by subject:

math score       100
reading score    100
writing score    100
dtype: int64

In [42]:
print("Minimum score by subject:")
df[["math score", "reading score", "writing score"]].min()

Minimum score by subject:

math score        0
reading score    17
writing score    10
dtype: int64

In [43]:
# Corellation

print("Corellation: ")
df[["math score", "reading score", "writing score"]].corr()

Corellation:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [44]:
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50 , "Yes", "No")

print("New columns preview (total, average, passed): ")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes

In [45]:
test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
print("students score by preparation course:")
print(test_prep_group)

# Gender-based average
gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("students score by gender:")
print(gender_avg)

#Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) *100
print("Pass rate:", pass_rate)

students score by preparation course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
students score by gender:
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
Pass rate: passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64

In [49]:
 # Convert scores to Numpy array
scores = df[["math score", "reading score", "writing score"]].values

 # Mean, Std Devitation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

 # Z-scores (normalize)
z_score  = (scores-np.mean(scores, axis=0))/np.std(scores, axis=0)
print("Z-score (normalized numbers):", np.mean(scores, axis=0))
print(z_score[:5])

 #Averange 0
 #Negative -
 #Positive +

Numpy Mean: [66.089 69.169 68.054]
Numpy Std: [15.15549666 14.59289002 15.18805728]
Z-score (normalized numbers): [66.089 69.169 68.054]
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]

In [55]:
# How many students above 90+ average?
top_scorers = df[df['average score'] >= 90]
print("Top scored students above 90:", len(top_scorers))

# How many students failed
failed = df[df['passed'] == "No"]
print("Failed students:", len(failed))

Top scored students above 90: 52
Failed students: 103

Top scored student above 90: 52